apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pvc-shrink-ray
  namespace: openshift-cnv
  labels:
    app: pvc-shrink-ray
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: pvc-shrink-ray
