apiVersion: v1
kind: ServiceAccount
metadata:
  name: pvc-shrink-ray
  namespace: openshift-cnv
  labels:
    app: pvc-shrink-ray
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pvc-shrink-ray
  labels:
    app: pvc-shrink-ray
rules:
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pvc-shrink-ray
  labels:
    app: pvc-shrink-ray
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pvc-shrink-ray
subjects:
  - kind: ServiceAccount
    name: pvc-shrink-ray
    namespace: openshift-cnv
